services:
  backend:
    build:
      target: production
    volumes: [] # Production doesn't need host volumes
    environment:
      - NODE_ENV=production

  frontend:
    build:
      target: production
    volumes: []
    ports:
      - "5173:80" # Map host 5173 to Nginx port 80
    environment:
      - NODE_ENV=production
